services:
  - type: web
    name: weather-ai-bot
    env: java
    buildCommand: ./mvnw clean package
    startCommand: java -jar target/*.jar
    envVars:
      - key: GOOGLE_AI_GEMINI_API_KEY
        from: GOOGLE_AI_GEMINI_API_KEY
      - key: WEATHERAPI_API_KEY
        from: WEATHERAPI_API_KEY
      - key: SERVER_PORT
        value: "8080"
