name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw
    
    - name: Build with Maven
      run: ./mvnw clean package
    
    - name: Run Tests  
      run: ./mvnw test
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: weather-ai-bot-jar
        path: target/*.jar
  deploy:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main'
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Download Artifact
      uses: actions/download-artifact@v4
      with:
        name: weather-ai-bot-jar
    
    - name: Deploy to Render
      # Only run this step if the branch is main
      if: github.ref == 'refs/heads/main'
      env:
          deploy_url: ${{ secrets.RENDER_API_KEY }}
      run: |
          curl "$deploy_url"
      