name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
        cache: maven
    
    - name: Make Maven wrapper executable
      run: chmod +x ./mvnw
    
    - name: Build with Maven
      run: ./mvnw clean package
    
    - name: Run Tests  
      run: ./mvnw test
    
    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: weather-ai-bot-jar
        path: target/*.jar